### ISSUE TITLE
Wrong name for 1.5.4 arm64 tar file

### ISSUE THREAD

**Issue by JavierLuna** [alexellis/containerd-arm#1]
In the [1.5.4 release](https://github.com/alexellis/containerd-arm/releases/tag/v1.5.4) the tar file for the arm64 binary is named containerd-**1.3.5**-linux-arm64.tar.gz  instead of the desired containerd-**1.5.4**-linux-arm64.tar.gz.

That is causing [faasd's ./hack/install.sh](https://github.com/openfaas/faasd/blob/master/hack/install.sh#L88) to do a broken installation: The `curl` resolves to a `Not Found` and subsequently `tar -xvz` complains. Because the `install.sh` script doesn't fail on errors, it leads to a broken installation although users are never warned. 

I may want to work on the `install.sh` script to handle this errors a bit better and try to resolve the versions without hardcoding them, if you think it'll be worth it I'll open up an issue to drive the discussion 😄

**Comment by tomaswarynyca** [comment]
Hello @alexellis, could you give a solution to this problem?

**Comment by alexellis** [comment]
Thanks for flagging this @JavierLuna 

It's probably best for you and or @tomaswarynyca to make use of Slack or to raise an issue on the faasd repo. This one has very little traffic, other than serving the download requests.

I've now fixed this.

**Comment by alexellis** [comment]
https://slack.openfaas.io/

If you'd like to contribute, please take a look at: https://github.com/openfaas/faasd/issues/214
